language: java
jdk:
  - oraclejdk8

addons:
  sonarqube:
    organization: "ksokol-github"
    token:
      secure: "yt6dNggEKRWUiZD9ZU6cgfF2rLhokoV79pD8n6Qr8180LxB26Mg8u3Hulh+Akzu5/6WmUIPxKW0RZbWZgEl2aqjTYuKYvX90b7J5FUq0YAHJWTiar9b3gMCwUUHeXovDBXsDPdsirxBokG9Z0l4iSuMxA1F0S7McqqDJuAdU0yBrf+Wnf06wbJNOUlfYT2uwK1lMjpHYS9XAkBJ+TY3rnCRdBK3bEineTNkJ0+PiafLe6khb5Ha87Xdsq3qxy6HqdQ4if7HwSO5nGAkmAAYgUMZLNjYYMdHBr2P52iKmlyeGKSefkMpksnUKog6Z8fyfljeSfYPWdYKuDJrfJbIiV9Lor4220sl3pFoZlPngtLfnIuVXwe7hfPaF8QqgYcxoafgnDMQBvwcSkYhA/WONHoHbxwV0mimfIrExMdZ/rzYmOzr0+iCuooH2eFVU3wmSOUD14btG49PtrSds64xHLZlEOeGcnD1XeIWkFX8mSin88Lefu+eLL0NtzTVNXKhIsuFxPozwLL19SzR3uP0G1ce9mMm7xNYNzAyPA1OlS1godt7+nEOpsIw2lWuZIHKwGqpS47W1TCtNkmMPlTgLEja5jaxkmPfsq1um+5cj8xKunesuV20bGZZAiD2WPgVU2rZNH9zXhipaV0KxBTZHC9CKsyhnjhzFUbjd7I4DTns="
    github_token:
      secure: "k3TeyQWWpfjQbtiPA+5pezm7wRHwlET/I4Hod9XHoqst5shxQPt3z5ZeDFJLrGbmFLsO0p9xtW8YO2HSIj2SN5b3mATOVkZg4rudiG/LPWG6/U3QFUVSYR41M1LQynnaXL6emUP/hYEtj0TwvzDLETrybfjKVCAhC8cks8XuWEcJQjQMr+VyQGcrJLw9VuZBc0aiRehF24HuPJV+PQo3qCMb+9zHi0xZ1bLL3N6KbwTA+QbfIFGvwFeuRmL1xT/wr8iY6Ua2LZ/II0dKJCTWmaEiLvrxANQ1pV95UfUd0TwYWKgA4gsUsYL7rsl2ss8PY+H/QUcdc6X9NxZ1WJW3C+lhDbmmrlpVNF55/rjkWsXJpX1Kp70KjkxYPV/+TVnxoCjlc/zOHTgcqkuMHHmhb7ISYCnb+hVRrZPEaIVXAIWx+FN4Z+uDaaPiofDYVEHvZsKuXjfDbrrpI1tCehpTCZfEV8HCxbKL+fMGg6S7q51QYcgmi7IUnh49pl/2C1G+5vkWuiv/N5T6+wHf8WA7+Jmc0yN0MBENxHX0tuFrNVHsiCzdf7gS7/N6bakcAFdg1FeuYwY92QCFGSbFtE7e6TzU51u54Xie1XT7HvunxQWdS+e7s8Y7BrKXlsHImdwLHtIWqcJH1w9kzK99wgbbDz8bQfD5nip87jKpYvRnKWg="

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/mailsink/node_modules'

script:
    - git fetch --unshallow # necessary for SonarQube blame information
    - ./mvnw verify sonar:sonar
