name: CI

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-jar:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Set up build environment
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Maven Directory
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: m2

      - name: Cache Node Modules Directory
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node

      - name: Build jar
        run: ./mvnw verify

      - uses: actions/upload-artifact@master
        with:
          name: mailsink
          path: target/mailsink.jar

      # - name: Sonar Cache Directory
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.sonar/cache
      #     key: sonar

      # - name: Check Project
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   run: ./mvnw verify sonar:sonar

  build-docker:
    needs: build-jar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@master
        with:
          name: mailsink
          path: target/mailsink.jar

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.1.0
        with:
          push: true
          tags: gbtec-ag/mailsink:latest

